stages:
  - build
  - stage
  - deploy

image: docker:latest

services:
  - docker:dind

# Can use UI to hide passwords
variables:
  IMAGE_NAME: hotrod-driver
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_USER: willwangkelda
  REDIS_PASS: keldakelda
  KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
  KUBE_NAMESPACE: hotrod
  EXTERNAL_REDIS_HOST: 10.0.0.11
  EXTERNAL_REDIS_PORT: 6379

before_script:
  - apk update && apk add curl bash openssl
  - curl -LO $KUBECTL_URL
  - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
  - mkdir -p $HOME/.kube
  - cat $KUBECONFIG > $HOME/.kube/config

build:
  stage: build
  before_script:
  - echo "skip before_script"
  script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  # Build hotrod image
  - docker pull $DOCKER_USER/$IMAGE_NAME:latest
  - docker build
    -t $DOCKER_USER/$IMAGE_NAME:$CI_COMMIT_SHA
    --cache-from $DOCKER_USER/$IMAGE_NAME:latest
    --build-arg git_pass=$GITLAB_TOKEN
    --build-arg build_time=$(date +%s) .
  - docker push $DOCKER_USER/$IMAGE_NAME:$CI_COMMIT_SHA
  - docker tag $DOCKER_USER/$IMAGE_NAME:$CI_COMMIT_SHA  $DOCKER_USER/$IMAGE_NAME:latest
  - docker push $DOCKER_USER/$IMAGE_NAME:latest

stage:
  stage: stage
  environment:
      name: StageEnv
  script:
    - sed -i -e s/COMMITID/$CI_COMMIT_SHA/g hotrod.yaml
    - sed -i -e s/GITLAB_CI_ENV_SLUG/$CI_ENVIRONMENT_SLUG/g hotrod.yaml
    - sed -i -e s/APPLICATION_TRACK/stable/g hotrod.yaml
    - sed -i -e s/REPLICA_COUNT/3/g hotrod.yaml
    - kubectl apply -f hotrod.yaml --namespace $KUBE_NAMESPACE
    - kubectl set env deployment/$CI_ENVIRONMENT_SLUG-$IMAGE_NAME
      REDIS_MASTER_PASSWORD=$REDIS_PASS --namespace $KUBE_NAMESPACE

production:
  stage: deploy
  environment:
      name: ProdEnv
  script:
    - sed -i -e s/COMMITID/$CI_COMMIT_SHA/g hotrod.yaml
    - sed -i -e s/GITLAB_CI_ENV_SLUG/$CI_ENVIRONMENT_SLUG/g hotrod.yaml
    - sed -i -e s/APPLICATION_TRACK/stable/g hotrod.yaml
    - sed -i -e s/REPLICA_COUNT/3/g hotrod.yaml
    - kubectl apply -f hotrod.yaml --namespace $KUBE_NAMESPACE
    - kubectl set env deployment/$CI_ENVIRONMENT_SLUG-$IMAGE_NAME
      HOTROD_REDIS_MASTER_SERVICE_HOST=$EXTERNAL_REDIS_HOST
      HOTROD_REDIS_MASTER_SERVICE_PORT=$EXTERNAL_REDIS_PORT
      --namespace $KUBE_NAMESPACE